repos:
  - repo: local
    hooks:
      - id: commit-msg-sign
        name: "Sign commit with 'edited by benarbidorra'"
        entry: bash scripts/sign-commit.sh
        language: system
        stages: [commit]
